### Register a new User & send validation email (with body)
POST {{base_url}}/register
Content-Type: application/json

{
  "email": "{{user.email}}",
  "password": "{{user.password}}"
}

### Validate a user using the activation link in the email received after registration
GET {{base_url}}/verify?token={{user.verify_token}}

### Login + creates an IntelliJ variable "auth_token" for next requests
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "{{user.email}}",
  "password": "{{user.password}}"
}

> {% client.global.set("access_token", response.body.token); %}

### Logout
GET {{base_url}}/logout
Authorization: Bearer {{access_token}}

### (remove later) Protected route for authenticated user:
GET {{base_url}}/protected
Authorization: Bearer {{access_token}}

