### Register a new User & send validation email (with body)
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "{{user.email}}",
  "password": "{{user.password}}"
}

### Validate a user using the activation link in the email received after registration
GET {{base_url}}/auth/verify?token={{user.verify_token}}

### Login + creates an IntelliJ variable "auth_token" for next requests
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "{{user.email}}",
  "password": "{{user.password}}"
}

> {% client.global.set("token", response.body.token); %}

### Logout
GET {{base_url}}/auth/logout
Authorization: Bearer {{token}}

### Get all users (authed)
GET {{base_url}}/users
Authorization: Bearer {{token}}
